name: Flutter iOS Build (Unsigned IPA)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      # 设置Dart环境，有助于后续获取Flutter版本相关操作
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install dependencies
        run: flutter pub get
        
      - name: Check current working directory
        run: pwd

      - name: Build iOS IPA (Unsigned)
        run: flutter build ios --release --no-tree-shake-icons --no-codesign
        working-directory:

      # 重命名IPA文件（根据构建输出路径来获取和处理IPA文件）
      - name: Rename IPA file
        run: |
          # 构建信息显示IPA相关文件在build/ios/iphoneos/目录下，这里获取该目录下的IPA文件名（假设只有一个IPA文件生成）
          IPA_FILE=$(ls build/ios/iphoneos/*.app)
          # 定义新的文件名，这里示例为添加版本号等信息，可按需修改
          NEW_IPA_FILE="muusic_${{ github.run_id }}.app"
          mv $IPA_FILE $NEW_IPA_FILE

      # 创建GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.run_id }}
          release_name: "Release ${{ github.run_id }}"
          draft: false
          prerelease: false
          token: ${{ secrets.g123 }}

      # 上传IPA文件到GitHub Release（准确填写IPA文件实际路径）
      - name: Upload IPA to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/ios/iphoneos/your_app_name_${{ github.run_id }}.app
          asset_name: music_${{ github.run_id }}.app
          asset_content_type: application/octet-stream
