name: Flutter iOS Build (Unsigned IPA)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      # 设置Dart环境，有助于后续获取Flutter版本相关操作
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install dependencies
        run: flutter pub get
        
      - name: Check current working directory
        run: pwd

      - name: Build iOS IPA (Unsigned)
        run: flutter build ios --release --no-tree-shake-icons --no-codesign
        working-directory:

      # 创建GitHub Release，将版本号硬编码为1.0
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 1.0
          name: v1.0
          draft: false
          prerelease: false
          token: ${{ secrets.G123 }}

      # 上传IPA文件到GitHub Release（使用构建输出的原始文件名及路径）
      - name: Upload IPA to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/ios/iphoneos/Runner.app
          asset_name: Runner.app
          asset_content_type: application/octet-stream
