name: Flutter iOS Build (Unsigned IPA)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      # 设置Dart环境，有助于后续获取Flutter版本相关操作
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      # 设置最新稳定的Xcode版本
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      # 安装Flutter项目依赖
      - name: Install dependencies
        run: flutter pub get


      - name: Build iOS IPA (Unsigned)
        run: flutter build ios --release --no-tree-shake-icons --no-codesign --output.
        working-directory: <实际项目根目录路径，如果默认没问题可不改>
