name: Flutter iOS Build (Unsigned IPA)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 设置Flutter环境
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      # 设置Java环境
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # 设置Xcode环境，这里可按需指定合适的Xcode版本号
      - name: Set up Xcode
        uses: actions/setup-xcode@v1
        with:
          xcode-version: '14.3'

      # 安装Flutter项目依赖
      - name: Install dependencies
        run: flutter pub get

   

      # 构建无签名的iOS IPA
      - name: Build iOS IPA (Unsigned)
        run: flutter build ios --no-codesign
        working-directory:.
